config/routes.rb
Rails.application.routes.draw do

  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root to: 'home#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products,            only: [:show, :index]
    resources :categories,          only: [:show, :index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/option_value_decorator.rb
Spree::OptionValue.class_eval do
  scope :load_by_option_type_id, -> option_type_id { where(option_type_id: option_type_id) }
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  scope :eager_load_products, -> { includes(master: [:default_price, :images]) }
  scope :limit_products_by_today, -> { where('available_on < ?', Time.now) }
  scope :load_by_taxon, -> taxon { where(spree_taxons: { id: taxon.id }) }
  scope :load_by_taxons, -> taxon { where(spree_taxons: { id: taxon.ids }) }
  scope :load_descendants, -> taxon { where(spree_taxons: { id: [taxon.descendants] }) }
  scope :load_by_product, -> product { where(spree_taxons: { id: product.taxon_ids }) }
  scope :exclude_self, -> product { where.not(spree_products: { id: product.id }) }

  class << self
    def load_products(taxon)
      if taxon.leaf?
        eager_load_products.load_by_taxon(taxon)
      else
        eager_load_products.load_descendants(taxon)
      end
    end

    def limit_products(product, max_display)
      eager_load_products.exclude_self(product).limit(max_display).uniq
    end

    def load_related_products(product, max_display)
      joins(:taxons).load_by_product(product).limit_products(product, max_display)
    end

    def load_new_products(max_display)
      eager_load_products.eager_load_products.limit_products_by_today.
        limit(max_display).order(available_on: :desc)
    end

    def limit_load_by_taxon(taxon, max_display)
      load_by_taxons(taxon).limit(max_display)
    end
  end
end

app/models/spree/taxon_decorator.rb
Spree::Taxon.class_eval do
  scope :load_by_variant, -> variant { where(spree_products: { id: variant.product_id }) }
end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do
  scope :load_by_option_values, -> id { where(spree_option_values: { id: id }) }
  scope :load_by_option_values_name, -> name { where(spree_option_values: { name: name }) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/sidebar.rb
module Sidebar
  extend ActiveSupport::Concern
  COLOR_ID = 2

  def taxonomies
    Spree::Taxonomy.includes(:taxons)
  end

  def colors
    Spree::OptionValue.load_by_option_type_id(COLOR_ID)
  end
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  include Sidebar
  before_action :set_sidebar_variables

  def index
    @variants = Spree::Variant.joins(:option_values).
      load_by_option_values_name(params[:color]).to_a.uniq { |color| color.name }
  end

  def show
    @taxon = Spree::Taxon.find(params[:id])

    @products = Spree::Product.joins(:taxons).load_products(@taxon)
  end

  def set_sidebar_variables
    @taxonomies = taxonomies

    @colors_in_sidebar = colors
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  MAX_NEW_PRODUCTS = 8

  def index
    @new_products = Spree::Product.load_new_products(MAX_NEW_PRODUCTS)
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  MAX_RELATED_PRODUCTS = 8

  def index
    @variant = Spree::Variant.find(params[:id])

    taxon = Spree::Taxon.joins(:products).load_by_variant(@variant)

    @related_products = Spree::Product.joins(:taxons).
      limit_load_by_taxon(taxon, MAX_RELATED_PRODUCTS)
  end

  def show
    @product = Spree::Product.find(params[:id])

    @related_products = Spree::Product.joins(:taxons).
      load_related_products(@product, MAX_RELATED_PRODUCTS)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  layout "sample_layout"

  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title:)
    base_title = 'BIGBAG Store'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <!-- SITE TITTLE -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(page_title: yield(:page_title)) %></title>

    <!-- PLUGINS CSS STYLE -->

    <!-- GOOGLE FONT -->
    <%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>

    <!-- CUSTOM CSS -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="main-wrapper">
      <%= render 'potepan/shared/header' %>
      <%= yield %>
      <%= render 'potepan/shared/footer' %>
      <%= render 'potepan/shared/copy_right' %>
    </div>
    <%= render 'potepan/modals/login_modal' %>
    <%= render 'potepan/modals/sign_up_modal' %>
    <%= javascript_include_tag 'application' %>
  </body>

</html>

app/views/layouts/sample_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Potepanec</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/potepan/categories/_products.html.erb
<div class="col-sm-4 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
        <%= image_tag(product.images.first.attachment(:product)) %>
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
          <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
          <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
        </ul>
      </div>
    </div>
      <div class="productCaption clearfix">
          <%= link_to potepan_product_path(product.id) do %>
          <h5><%= product.name %></h5>
          <% end %>
        <h3><%= product.display_price %></h3>
      </div>
    </div>
  </div>

app/views/potepan/categories/_variants.html.erb
<div class="col-sm-4 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
        <%= image_tag(variant.images.first.attachment(:product)) %>
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
          <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
          <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
        </ul>
      </div>
    </div>
      <div class="productCaption clearfix">
          <%= link_to :controller => "products", :action => "index", id: variant.id do %>
          <h5><%= variant.name %></h5>
          <% end %>
        <h3><%= variant.display_price %></h3>
      </div>
    </div>
  </div>

app/views/potepan/categories/index.html.erb
<% provide(:title) %>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <%= render 'potepan/shared/sidebar_categories' %>
        <%= render 'potepan/shared/sidebar_price' %>
        <%= render 'potepan/shared/sidebar_color' %>
        <%= render 'potepan/shared/sidebar_size' %>
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <div class="col-xs-6">
            <select name="guiest_id1" id="guiest_id1" class="select-drop">
              <option value="0">並び替え</option>
              <option value="1">人気順</option>
              <option value="2">安い順</option>
              <option value="3">新着順</option>
              <option value="3">高い順</option>
            </select>
          </div>
          <div class="col-xs-6">
            <div class="btn-group pull-right" role="group">
              <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
              <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
            </div>
          </div>
        </div>
        <div class="row">
          <%= render partial: "variants", collection: @variants, as: :variant %>
        </div>
      </div>
    </div>
  </div>
</section>


<!-- LIGHT SECTION -->
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/show.html.erb
<% provide(:title, @taxon.name) %>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <%= render 'potepan/shared/sidebar_categories' %>
        <%= render 'potepan/shared/sidebar_price' %>
        <%= render 'potepan/shared/sidebar_color' %>
        <%= render 'potepan/shared/sidebar_size' %>
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <div class="col-xs-6">
            <select name="guiest_id1" id="guiest_id1" class="select-drop">
              <option value="0">並び替え</option>
              <option value="1">人気順</option>
              <option value="2">安い順</option>
              <option value="3">新着順</option>
              <option value="3">高い順</option>
            </select>
          </div>
          <div class="col-xs-6">
            <div class="btn-group pull-right" role="group">
              <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
              <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
            </div>
          </div>
        </div>
        <div class="row">
          <%= render partial: "products", collection: @products, as: :product %>
        </div>
      </div>
    </div>
  </div>
</section>


<!-- LIGHT SECTION -->
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/home/_banner.html.erb
<!-- BANNER -->
<div class="bannercontainer">
  <div class="fullscreenbanner-container">
    <div class="fullscreenbanner">
      <ul>
        <li data-transition="slidehorizontal" data-slotamount="5" data-masterspeed="700" data-title="Slide 1">
          <%= image_tag("home/banner-slider/slider-bg.jpg", :alt => "slidebg1", data:{bgposition: "center center", bgfit: "cover" , bgrepeat: "no-repeat"}) %>
          <div class="slider-caption container">
            <div class="tp-caption rs-caption-1 sft start"
              data-hoffset="0"
              data-x="370"
              data-y="54"
              data-speed="800"
              data-start="1500"
              data-easing="Back.easeInOut"
              data-endspeed="300">
              <%= image_tag("home/banner-slider/shoe1.png", :alt => "slider-image") %>
            </div>

            <div class="tp-caption rs-caption-2 sft"
              data-hoffset="0"
              data-y="119"
              data-speed="800"
              data-start="2000"
              data-easing="Back.easeInOut"
              data-endspeed="300">
              Canvas Sneaker
            </div>

            <div class="tp-caption rs-caption-3 sft"
              data-hoffset="0"
              data-y="185"
              data-speed="1000"
              data-start="3000"
              data-easing="Power4.easeOut"
              data-endspeed="300"
              data-endeasing="Power1.easeIn"
              data-captionhidden="off">
              Exclusive to <br>
              BigBag <br>
              <small>Spring / Summer 2020</small>
            </div>
            <div class="tp-caption rs-caption-4 sft"
              data-hoffset="0"
              data-y="320"
              data-speed="800"
              data-start="3500"
              data-easing="Power4.easeOut"
              data-endspeed="300"
              data-endeasing="Power1.easeIn"
              data-captionhidden="off">
              <span class="page-scroll"><a href="single_product.html" class="btn primary-btn">Buy Now<i class="glyphicon glyphicon-chevron-right"></i></a></span>
            </div>
          </div>
        </li>
        <li data-transition="slidehorizontal" data-slotamount="5" data-masterspeed="1000" data-title="Slide 2">
          <%= image_tag("home/banner-slider/slider-bg.jpg", :alt => "slidebg", data:{bgposition: "center center", bgfit: "cover" , bgrepeat: "no-repeat"}) %>
          <div class="slider-caption container captionCenter">
            <div class="tp-caption rs-caption-1 sft start captionCenterAlign"
              data-x="center"
              data-y="228"
              data-speed="800"
              data-start="1500"
              data-easing="Back.easeInOut"
              data-endspeed="300">
              <%= image_tag("home/banner-slider/shoe2.png", :alt => "slider-image") %>
            </div>

            <div class="tp-caption rs-caption-2 sft captionCenterAlign"
              data-x="center"
              data-y="50"
              data-speed="800"
              data-start="2000"
              data-easing="Back.easeInOut"
              data-endspeed="300">
              Exclusive to BigBag
            </div>

            <div class="tp-caption rs-caption-3 sft captionCenterAlign"
              data-x="center"
              data-y="98"
              data-speed="1000"
              data-start="3000"
              data-easing="Power4.easeOut"
              data-endspeed="300"
              data-endeasing="Power1.easeIn"
              data-captionhidden="off">
              Canvas Sneaker
            </div>

            <div class="tp-caption rs-caption-4 sft captionCenterAlign"
              data-x="center"
              data-y="156"
              data-speed="800"
              data-start="3500"
              data-easing="Power4.easeOut"
              data-endspeed="300"
              data-endeasing="Power1.easeIn"
              data-captionhidden="off">
              <span class="page-scroll"><a href="single_product.html" class="btn primary-btn">Buy Now<i class="glyphicon glyphicon-chevron-right"></i></a></span>
            </div>
          </div>
        </li>
        <li data-transition="slidehorizontal" data-slotamount="5" data-masterspeed="700"  data-title="Slide 3">
          <%= image_tag("home/banner-slider/slider-bg.jpg", :alt => "slidebg", data:{bgposition: "center center", bgfit: "cover" , bgrepeat: "no-repeat"}) %>
          <div class="slider-caption container">
            <div class="tp-caption rs-caption-1 sft start"
              data-hoffset="0"
              data-x="0"
              data-y="85"
              data-speed="800"
              data-start="1500"
              data-easing="Back.easeInOut"
              data-endspeed="300">
              <%= image_tag("home/banner-slider/shoe3.png", :alt => "slider-image") %>
            </div>

            <div class="tp-caption rs-caption-2 sft "
              data-hoffset="0"
              data-y="119"
              data-x="800"
              data-speed="800"
              data-start="2000"
              data-easing="Back.easeInOut"
              data-endspeed="300">
              Canvas Sneaker
            </div>

            <div class="tp-caption rs-caption-3 sft"
              data-hoffset="0"
              data-y="185"
              data-x="800"
              data-speed="1000"
              data-start="3000"
              data-easing="Power4.easeOut"
              data-endspeed="300"
              data-endeasing="Power1.easeIn"
              data-captionhidden="off">
              Exclusive to <br>
              BigBag <br>
              <small>Spring / Summer 2020</small>
            </div>

            <div class="tp-caption rs-caption-4 sft"
              data-hoffset="0"
              data-y="320"
              data-x="800"
              data-speed="800"
              data-start="3500"
              data-easing="Power4.easeOut"
              data-endspeed="300"
              data-endeasing="Power1.easeIn"
              data-captionhidden="off">
              <span class="page-scroll"><a href="single_product.html" class="btn primary-btn">Buy Now<i class="glyphicon glyphicon-chevron-right"></i></a></span>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/home/_new_products.html.erb
<div class="slide">
  <div class="productImage clearfix">
    <%= image_tag(new_product.images.first.attachment(:product)) %>
    <div class="productMasking">
      <ul class="list-inline btn-group" role="group">
        <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
        <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
        <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-eye"></i></a></li>
      </ul>
    </div>
  </div>
  <div class="productCaption clearfix">
    <%= link_to potepan_product_path(new_product.id) do %>
      <h5><%= new_product.name %></h5>
    <% end %>
    <h3><%= new_product.display_price %></h3>
  </div>
</div>

app/views/potepan/modals/_login_modal.html.erb
<!-- LOGIN MODAL -->
<div class="modal fade login-modal" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">Enter Email</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">Password</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/potepan/modals/_product_quick_view_modal.html.erb
<!-- PORDUCT QUICK VIEW MODAL -->
<div class="modal fade quick-view" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div class="media">
          <div class="media-left">
            <%= image_tag("img/products/quick-view/quick-view-01.jpg", :class => "media-object", :alt => "Image") %>
          </div>
          <div class="media-body">
            <h2>Old Skool Navy</h2>
            <h3>$149</h3>
            <p>Classic sneaker from Vans. Cotton canvas and suede upper. Textile lining with heel stabilizer and ankle support. Contrasting laces. Sits on a classic waffle rubber sole.</p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">Size</option>
                <option value="1">Size 1</option>
                <option value="2">Size 2</option>
                <option value="3">Size 3</option>
              </select>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <option value="0">Qty</option>
                <option value="1">Qty 1</option>
                <option value="2">Qty 2</option>
                <option value="3">Qty 3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="#" class="btn btn-primary btn-block">Add to cart <i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/potepan/products/_related_products.html.erb
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
      <%= image_tag(featured_product.images.first.attachment(:small)) %>
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
          <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
          <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="productCaption clearfix">

     <h5><%= link_to featured_product.name, potepan_product_path(featured_product.id) %></h5>
     <h3><%= featured_product.price %></h3>
    </div>
  </div>
</div>

app/views/potepan/shared/_sidebar_categories.html.erb
<div class="panel panel-default">
  <div class="panel-heading">商品カテゴリー</div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav">
        <% @taxonomies.each do |taxonomy| %>
          <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#<%= taxonomy.id %>">
              <%= taxonomy.name %>
              <i class="fa fa-plus"></i>
            </a>
            <ul id="<%= taxonomy.id %>" class="collapse collapseItem">
              <% taxonomy.root.leaves.each do |taxon| %>
                <li>
                  <%= link_to potepan_category_path(taxon.id) do %>
                  <i class="fa fa-caret-right" aria-hidden="true"></i>
                  <%= taxon.name %>
                  <span>（<%= taxon.products.count %>）</span>
                </li>
              <% end %>
            <% end %>
          </ul>
        </li>
      <% end %>
    </ul>
  </div>
</div>
</div>